# Aula07.Ex03 - A matriz View - Passo a passo

### Primeiro, vamos importar as bibliotecas necessárias.
Verifique no código anterior um script para instalar as dependências necessárias (OpenGL e GLFW) antes de prosseguir.

In [7]:
import numpy as np
import glm
import math

## Calculando Matriz View

In [8]:
cameraPos = np.array([0.0, 0.0, 2.0])
cameraTarget = np.array([0.0, 0.0, 0.0])
cameraUp = np.array([0.0, 1.0, 0.0])

n = cameraPos-cameraTarget
n = n / np.linalg.norm(n)
n

array([0., 0., 1.])

In [9]:
u = np.cross(cameraUp, n)
u = u / np.linalg.norm(u)
u

array([1., 0., 0.])

In [10]:
v = np.cross(n, u)
v

array([0., 1., 0.])

In [11]:
R = [
        [u[0], u[1], u[2], 0.0],
        [v[0], v[1], v[2], 0.0],
        [n[0], n[1], n[2], 0.0],
        [ 0.0,  0.0,  0.0, 1.0]
    ]

T = [
        [1.0, 0.0, 0.0, -cameraPos[0]],
        [0.0, 1.0, 0.0, -cameraPos[1]],
        [0.0, 0.0, 1.0, -cameraPos[2]],
        [0.0, 0.0, 0.0, 1.0          ],        
    ]

view = np.matmul(T,R)
view

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -2.],
       [ 0.,  0.,  0.,  1.]])

## Calculando Matriz View com GLM

In [12]:
cameraPos = glm.vec3(0.0, 0.0, 2.0)
cameraTarget = glm.vec3(0.0, 0.0, 0.0)
cameraUp = glm.vec3(0.0, 1.0, 0.0)

view = glm.lookAt(cameraPos, cameraTarget, cameraUp)
np.array(view).T

array([[ 1., -0.,  0., -0.],
       [ 0.,  1.,  0., -0.],
       [-0., -0.,  1., -2.],
       [ 0.,  0.,  0.,  1.]], dtype=float32)