# Aula07 - Transformações Geométricas 3D com a Biblioteca GLM

Nas aulas anteriores, nós calculamos as operações de transformações geométricas de translação, rotação e escala por meio de multiplicação de suas respectivas matrizes. É uma estratégia didática interessante, pois ao implementar tais operações, o estudante acompanha os detalhes envolvidos nas transformações.

A partir das aulas de Viewing 3D (Model, View e Projection) essas operações se tornarão muito mais frequentes e repetitivas. Dessa forma, agora iremos utilizar uma biblitoca de apoio chamada GLM (OpenGL Mathematics).

https://glm.g-truc.net/

## Instalando a biblioteca GLM

A GLM está disponível para linguagens C/C++, Java e Python.

* Usando GLM com GCC (https://github.com/g-truc/glm)
* Usando GLM com Python (https://pypi.org/project/PyGLM/): pip install pyglm
* Usando GLM com Java (https://github.com/kotlin-graphics/glm)

## Importando a biblioteca GLM (Python)

In [2]:
# !pip install pyglm
import glm
import numpy as np
import math

## Criando uma Matriz Identidade

Uma matriz identidade (4x4) é usualmente o ponto de partida para várias transformações geométricas 3D

In [3]:
matriz_identidade = glm.mat4(1.0)
matriz_identidade

mat4x4( 1, 0, 0, 0 | 0, 1, 0, 0 | 0, 0, 1, 0 | 0, 0, 0, 1 )

Podemos converter o GLM para a estrutura do Numpy, na qual estamos acostumados até o momento.

In [4]:
matriz_identidade_np = np.array(matriz_identidade).T # T obtem a transposta
matriz_identidade_np

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

## Translação

* Primeiro vamos gerar a matriz translação 3D
* Em seguida, vamos realizar a translação aplicando offsets em cada eixo: t_x, t_y, t_z

In [5]:
t_x = -0.2
t_y = +0.5
t_z = +0.7
matriz_translacao = glm.mat4(1.0) # inicializa uma matriz identidade
matriz_translacao = glm.translate(matriz_translacao, glm.vec3(t_x, t_y, t_z))  # aplica translacao com base nos offsets  
matriz_translacao

mat4x4( 1, 0, 0, 0 | 0, 1, 0, 0 | 0, 0, 1, 0 | -0.2, 0.5, 0.7, 1 )

Exibindo a matriz de translação no formato Numpy

In [6]:
matriz_translacao = np.array(matriz_translacao).T # T obtem a transposta
matriz_translacao

array([[ 1. ,  0. ,  0. , -0.2],
       [ 0. ,  1. ,  0. ,  0.5],
       [ 0. ,  0. ,  1. ,  0.7],
       [ 0. ,  0. ,  0. ,  1. ]], dtype=float32)

## Escala
* Primeiro vamos gerar a matriz rotação 3D
* Em seguida, vamos aplicar escala a partir dos fatores em cada eixo: s_x, s_y, s_z

In [7]:
s_x = 0.5
s_y = 1.5
s_z = 2.5

matriz_escala = glm.mat4(1.0) # inicializa uma matriz identidade
matriz_escala = glm.scale(matriz_escala, glm.vec3(s_x, s_y, s_z))  # aplica escala
matriz_escala

mat4x4( 0.5, 0, 0, 0 | 0, 1.5, 0, 0 | 0, 0, 2.5, 0 | 0, 0, 0, 1 )

In [8]:
matriz_escala = np.array(matriz_escala).T # T obtem a transposta
matriz_escala

array([[0.5, 0. , 0. , 0. ],
       [0. , 1.5, 0. , 0. ],
       [0. , 0. , 2.5, 0. ],
       [0. , 0. , 0. , 1. ]], dtype=float32)

## Rotação
* Primeiro vamos gerar a matriz rotação 3D
* Em seguida, vamos aplicar rotação dado um ângulo e os eixos de rotação.

In [9]:
# Definindo o ângulo de rotação
angulo = 30.0
angulo = math.radians(angulo)

# Definindo os eixos que serão rotacionados (1.0 ativa o eixo; 0.0 desativa o eixo)
# Abaixo, rotação no eixo z.
r_x = 0.0
r_y = 0.0
r_z = 1.0

matriz_rotacao = glm.mat4(1.0) # inicializa uma matriz identidade
matriz_rotacao = glm.rotate(matriz_rotacao, angulo, glm.vec3(r_x, r_y, r_z))  # aplica rotacao
matriz_rotacao

mat4x4( 0.866025, 0.5, 0, 0 | -0.5, 0.866025, 0, 0 | 0, 0, 1, 0 | 0, 0, 0, 1 )

In [10]:
matriz_rotacao = np.array(matriz_rotacao).T # T obtem a transposta
matriz_rotacao

array([[ 0.8660254, -0.5      ,  0.       ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]], dtype=float32)

## Multiplicando matrizes de transformação geométrica

As transformações podem ser aplicadas em sequência, com base na multiplicação de suas matrizes.

No exemplo a seguir, nós aplicamos rotação, seguida de translação e escala.

In [11]:
angulo = 30.0
angulo = math.radians(angulo)
    
matrix_transform = glm.mat4(1.0) # instanciando uma matriz identidade

# aplicando translacao
t_x = -0.2
t_y = +0.5
t_z = +0.7
matrix_transform = glm.translate(matrix_transform, glm.vec3(t_x, t_y, t_z))  

# aplicando rotacao no eixo y
r_x = 0.0
r_y = 1.0
r_z = 0.0
matrix_transform = glm.rotate(matrix_transform, angulo, glm.vec3(r_x, r_y, r_z))
    
# aplicando escala
s_x = 0.5
s_y = 1.5
s_z = 2.5
matrix_transform = glm.scale(matrix_transform, glm.vec3(s_x, s_y, s_z))
    
# transformacao final
matrix_transform

mat4x4( 0.433013, 0, -0.25, 0 | 0, 1.5, 0, 0 | 1.25, 0, 2.16506, 0 | -0.2, 0.5, 0.7, 1 )

Na matriz seguinte, estão embutidas as três operações anteriores.

In [12]:
matrix_transform = np.array(matrix_transform).T # pegando a transposta da matriz (glm trabalha com ela invertida)
matrix_transform

array([[ 0.4330127,  0.       ,  1.25     , -0.2      ],
       [ 0.       ,  1.5      ,  0.       ,  0.5      ],
       [-0.25     ,  0.       ,  2.1650634,  0.7      ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]], dtype=float32)